<a href="https://colab.research.google.com/github/suhasinijam/deep-learning-challenge/blob/main/Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df_new= application_df.drop(["EIN", "NAME"], axis=1)
application_df_new.columns

Index(['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE',
       'ORGANIZATION', 'STATUS', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS',
       'ASK_AMT', 'IS_SUCCESSFUL'],
      dtype='object')

In [3]:
# Determine the number of unique values in each column.
print(application_df_new.nunique())

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
df_app_count = application_df_new["APPLICATION_TYPE"].value_counts()
df_app_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(df_app_count [df_app_count  < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df_new['APPLICATION_TYPE'] = application_df_new['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df_new['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
df_calssification = application_df_new["CLASSIFICATION"].value_counts()
df_calssification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
df_classification_greater_than_1 = df_calssification[df_calssification > 1]
df_classification_greater_than_1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_types_to_replace = list(df_calssification [df_calssification  < 100].index)

# Replace in dataframe
for cls in classifications_types_to_replace:
    application_df_new['CLASSIFICATION'] = application_df_new['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df_new['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
df_dummies = pd.get_dummies(application_df_new)
df_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
y = df_dummies['IS_SUCCESSFUL'].values
X = df_dummies.drop('IS_SUCCESSFUL', axis=1).values
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78, stratify=y)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 20

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1,
             input_dim=number_input_features, activation="tanh"))


# Second hidden layer
nn.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer2, activation="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 10)                500

 dense_1 (Dense)             (None, 20)                220

 dense_2 (Dense)             (None, 1)                 21

=================================================================
Total params: 741 (2.89 KB)
Trainable params: 741 (2.89 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [14]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=25)

Epoch 1/25
804/804 [==============================] - 3s 3ms/step - loss: 0.6028 - accuracy: 0.6866
Epoch 2/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5644 - accuracy: 0.7257
Epoch 3/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5592 - accuracy: 0.7290
Epoch 4/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5561 - accuracy: 0.7286
Epoch 5/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5543 - accuracy: 0.7301
Epoch 6/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5524 - accuracy: 0.7299
Epoch 7/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5514 - accuracy: 0.7304
Epoch 8/25
804/804 [==============================] - 3s 4ms/step - loss: 0.5507 - accuracy: 0.7305
Epoch 9/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7301
Epoch 10/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7313
Epoch 11/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7308
Epoch 12/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5481 - accuracy: 0.7321
Epoch 13/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5477 - accuracy: 0.7325
Epoch 14/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7325
Epoch 15/25
804/804 [==============================] - 3s 3ms/step - loss: 0.5472 - accuracy: 0.7311
Epoch 16/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7325
Epoch 17/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7318
Epoch 18/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7334
Epoch 19/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7328
Epoch 20/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7331
Epoch 21/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7325
Epoch 22/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5457 - accuracy: 0.7323
Epoch 23/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7330
Epoch 24/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7330
Epoch 25/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7335

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5521 - accuracy: 0.7310 - 524ms/epoch - 2ms/step
Loss: 0.5521414875984192, Accuracy: 0.7309620976448059

In [19]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization2.keras')

In [20]:
# 2nd attempt:
#Increased layers
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 15
hidden_nodes_layer2 = 25
hidden_nodes_layer3 = 25
nn = tf.keras.models.Sequential()

In [21]:
# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1,
             input_dim=number_input_features, activation="tanh"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer2, activation="sigmoid"))

# 3rd hidden layer
nn.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# model structure
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 15)                750

 dense_4 (Dense)             (None, 25)                400

 dense_5 (Dense)             (None, 25)                650

 dense_6 (Dense)             (None, 1)                 26

=================================================================
Total params: 1826 (7.13 KB)
Trainable params: 1826 (7.13 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [23]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [25]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=25)

Epoch 1/25
804/804 [==============================] - 5s 3ms/step - loss: 0.5912 - accuracy: 0.7046
Epoch 2/25
804/804 [==============================] - 3s 3ms/step - loss: 0.5598 - accuracy: 0.7283
Epoch 3/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5551 - accuracy: 0.7305
Epoch 4/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5524 - accuracy: 0.7303
Epoch 5/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5514 - accuracy: 0.7301
Epoch 6/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5505 - accuracy: 0.7300
Epoch 7/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7303
Epoch 8/25
804/804 [==============================] - 3s 3ms/step - loss: 0.5485 - accuracy: 0.7325
Epoch 9/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5474 - accuracy: 0.7306
Epoch 10/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7313
Epoch 11/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7328
Epoch 12/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7325
Epoch 13/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7341
Epoch 14/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5454 - accuracy: 0.7339
Epoch 15/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5454 - accuracy: 0.7334
Epoch 16/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7335
Epoch 17/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7350
Epoch 18/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5441 - accuracy: 0.7348
Epoch 19/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7336
Epoch 20/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7353
Epoch 21/25
804/804 [==============================] - 3s 3ms/step - loss: 0.5431 - accuracy: 0.7345
Epoch 22/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7348
Epoch 23/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7352
Epoch 24/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7356
Epoch 25/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7355

In [27]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5470 - accuracy: 0.7321 - 1s/epoch - 5ms/step
Loss: 0.5470441579818726, Accuracy: 0.7321282625198364

In [29]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization2.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(